### PR TITLE
s3 sync drafted

### PR DESCRIPTION
**Pull request by vasi-grigo**

### CODE REVIEW

**Comment by sreddybr3** [comment]
how do we plan to provide S3 credentials for container ? ENV variables ?

**Comment by vasi-grigo** [comment]
IAM role

**Comment by vasi-grigo** [comment]
when outside of AWS (or working locally) - need to add creds

**Comment by sreddybr3** [comment]
can u change Dockerfile for GPU -> second stage to install awscli ?
same changes as done for CPU

**Pull request merged**
